# Generated by Django 4.2.14 on 2024-07-28 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='user_id1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_user1', to='users.user'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user_id2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_user2', to='users.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=models.URLField(),
        ),
    ]
